package ru.anafro.quark.server.console.commands;

import ru.anafro.quark.server.console.Command;
import ru.anafro.quark.server.console.CommandArguments;
import ru.anafro.quark.server.files.FileSystem;
import ru.anafro.quark.server.utils.containers.UniqueList;

public class ClearMavenOutputCommand extends Command {
    public ClearMavenOutputCommand() {
        super(
                new UniqueList<>(
                        "clear-maven-output",
                        "clear-maven-build-files",
                        "flush-maven-output",
                        "flush-maven-build-files",
                        "clean-maven-output",
                        "clean-maven-build-files",
                        "clear-maven",
                        "flush-maven",
                        "clean-maven"
                ),
                "Clears Maven build output",
                "Removes all the unnecessary files generated by Maven"
        );
    }

    @Override
    public void action(CommandArguments arguments) {
        FileSystem.deleteIfExists(
                "maven-status",
                "classes",
                "generated-sources",
                "maven-archiver",
                "maven-status"
        );
    }
}
