package ru.anafro.quark.server.console.commands;

import ru.anafro.quark.server.console.Command;
import ru.anafro.quark.server.console.CommandArguments;
import ru.anafro.quark.server.facade.Quark;

import static ru.anafro.quark.server.utils.collections.Collections.list;

public class ClearMavenOutputCommand extends Command {
    public ClearMavenOutputCommand() {
        super(
                list(
                        "clear-maven-output",
                        "clear-maven-build-files",
                        "flush-maven-output",
                        "flush-maven-build-files",
                        "clean-maven-output",
                        "clean-maven-build-files",
                        "clear-maven",
                        "flush-maven",
                        "clean-maven"
                ),
                "Clears Maven build output",
                "Removes all the unnecessary files generated by Maven"
        );
    }

    @Override
    public void action(CommandArguments arguments) {
        Quark.clearMavenOutput();
        logger.info("Maven output is cleared.");
    }
}
